export interface ISettings {
  strictMode: boolean;
  showFieldSummary: boolean;
  showGrid: boolean;
  snapToGrid: boolean;
  showDataTypes: boolean;
  mode: "light" | "dark";
  autosave: boolean;
  showCardinality: boolean;
  relationshipStyle: "erd" | "uml" | "idef1x" | "default";
  relationshipNameFontSize: number;
  relationshipSideLabelFontSize: number;
  showRelationshipLabels: boolean;
  showRelationshipNames: boolean;
  tableWidth: number;
  showDebugCoordinates: boolean;
  tableNamesUppercase: boolean;
  showPKIcons: boolean;
  showFKIcons: boolean;
  sideMargin: number;
  spreadRelations: boolean;
  tableColors: string[];
  outboundRelationsInTableColor: boolean;
  relationAnimationsInTableColor: boolean;
  autoSplitRelationships: boolean;
  renameFK: boolean;
  showDebugConsole: boolean;
  debugPath: boolean;
  settingsPosition: { x: number; y: number };
}
